name: Test dispatch

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - assigned
      - unassigned
      - edited
  push:

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo a string
        id: pod
        # shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: echo a string 2
        env:
          TEST: ${{ steps.pod.outputs.sha_short }}
        run: echo ${{ steps.pod.outputs.sha_short }}
      - name: (git remote show origin)
        run: echo "$(git remote show origin)"
      - name: Get branch name
        id: get-branch-name
        run: |
          # Extract branch name for push events
          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            echo "branch-name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          # Extract branch name for pull request events
          elif [[ "${GITHUB_REF}" == refs/pull/*/merge ]]; then
            echo "branch-name=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          fi
      - name: Display branch name
        run: echo "The branch name is ${{ steps.get-branch-name.outputs.branch-name }}"
      # - name: multiline script
      #   run: |
      #     node -v
      #     npm -v
      # - name: Sleep for 30 seconds
      #   run: sleep 10s
      #   shell: bash
      # - name: echo after delay
      #   run: echo "Hello After Delay"
